[package]
name = "uisuki"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
log = "0.4.22"
semver = "1.0.23"
iso8601 = "0.6.1"
shuttle-serenity = "0.48.0"
shuttle-runtime = "0.48.0"
poise = "0.6.1"
reqwest = "0.12.8"