[package]
name = "uisuki"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
log = "0.4.21"
semver = "1.0.22"
iso8601 = "0.6.1"
shuttle-serenity = "0.43.0"
shuttle-runtime = "0.43.0"

[dependencies.serenity]
version = "0.12.1"